### ISSUE TITLE
Program doesn't run

### ISSUE THREAD

**Issue by RoyDubnium** [mlugg/adrift#6]
I installed the relevant dependencies, built vtk from source, and then tried to run the adrift executable. I even tried building that from source, too, but whenever i tried, it just never opened, and there was no message in console. Not even a message in the terminal, unless i gave it working directory that didn't exist. Did i do something wrong? What am i supposed to do?
I'm using Linux Mint 21.2.

**Comment by RoyDubnium** [comment]
Nevermind, I just didn't understand what i was doing

**Comment by vulam49** [comment]
So what did you do?

**Comment by RoyDubnium** [comment]
The problem that I was having is (If memory serves), the actual splits, config and autosplitter executable weren't in the correct directory. They had to be in the current working directory for it to work. The issue I opened here was vague and uninformed, so I find it unlikely that you have the exact same issue.
